from __future__ import annotations

from typing import Any

from app.config import get_settings
from app.tools.composio_client import ComposioClient


def post_slack_message(
    text: str,
    channel_id: str | None = None,
    blocks: list[dict] | None = None,
    dry_run: bool | None = None,
    client: ComposioClient | None = None,
) -> dict[str, Any]:
    settings = get_settings()
    c = client or ComposioClient(dry_run=dry_run)
    channel = channel_id or settings.slack_channel_id

    params: dict[str, Any] = {"channel": channel, "text": text}
    if blocks:
        params["blocks"] = blocks

    return c.execute("SLACK_SENDS_A_MESSAGE_TO_A_SLACK_CHANNEL", params)


def build_research_summary_blocks(
    topic: str,
    insights: list[str],
    notion_url: str = "",
    github_url: str = "",
    linear_url: str = "",
) -> list[dict[str, Any]]:
    """Build Slack Block Kit payload for a rich research summary."""
    bullet_insights = "\n".join(f"• {i}" for i in insights[:5])
    links = []
    if notion_url:
        links.append(f"<{notion_url}|Notion Report>")
    if github_url:
        links.append(f"<{github_url}|GitHub Issue>")
    if linear_url:
        links.append(f"<{linear_url}|Linear Tasks>")
    link_text = "  |  ".join(links) if links else "_No links yet_"

    return [
        {
            "type": "header",
            "text": {"type": "plain_text", "text": f"Research Complete: {topic[:60]}"},
        },
        {"type": "divider"},
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Key Insights*\n{bullet_insights}"},
        },
        {
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Artifacts Created*\n{link_text}"},
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "_Generated by Enterprise Memory Execution Agent_",
                }
            ],
        },
    ]
